name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test_client:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install client dependencies
        run: cd client && npm install

      - name: Run client tests
        run: cd client && npm run test

  test_server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install server dependencies
        run: cd server && npm install

      - name: Run server tests
        run: cd server && npx jest
